name: Snyk Security & Code Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Node.js environment for your React app
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install npm dependencies
      - name: Install dependencies
        run: npm ci

      # Install the Snyk CLI globally
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Authenticate Snyk with your secret token
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # Run Snyk to test for known vulnerabilities in dependencies
      - name: Run Snyk Test
        run: snyk test

      # Optionally, run Snyk Code to perform static analysis (outputs SARIF for integration)
      - name: Run Snyk Code Test
        run: snyk code test --sarif > snyk-code.sarif
